name: Deploy

on:
  push:
    branches:
      - "main"
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read
defaults:
  run:
    working-directory: "./hello_world"
env:
  PYTHON_VERSION: 3.13
  function-name: sample-actions-deploy-function
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: Build
        run: pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.deploy_role }}
          aws-region: ap-northeast-1

      - name: Deploy
        uses: aws-actions/aws-lambda-deploy@v1.0.1
        with:
          function-name: ${{ env.function-name }}
          ## working-directoryからの相対ではなくリポジトリ直下基準で判定していたので明示的に指定
          code-artifacts-dir: ./hello_world
          handler: app.lambda_handler
          runtime: python${{ env.PYTHON_VERSION }}
          role: ${{ secrets.LAMBDA_ROLE_ARN }}
