name: Deploy Multiple Lambdas

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "**/*.py"
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  PYTHON_VERSION: 3.13
  lambda-role-arn: ${{ secrets.LAMBDA_ROLE_ARN }}

jobs:
  deploy-lambdas:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          # - name: hello-lambda-function
          #   directory: ./hello_lambda
          #   handler: app.lambda_handler
          # - name: hello-slack-function
          #   directory: ./hello_slack
          #   handler: app.lambda_handler
          - name: slack-get_reactions_function
            directory: ./get_reactions
            handler: app.lambda_handler
          - name: slack-get_messages_function
            directory: ./get_messages
            handler: app.lambda_handler

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Build ${{ matrix.function.name }}
        run: |
          cd ${{ matrix.function.directory }}
          if [ -f requirements.txt ]; then
            # 依存関係を関数ディレクトリにインストール
            pip install -r requirements.txt -t .
            # __pycache__ディレクトリを削除（不要なファイル）
            find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
            find . -name "*.pyc" -delete 2>/dev/null || true
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy ${{ matrix.function.name }}
        uses: aws-actions/aws-lambda-deploy@v1.0.1
        with:
          function-name: ${{ matrix.function.name }}
          code-artifacts-dir: ${{ matrix.function.directory }}
          handler: ${{ matrix.function.handler }}
          runtime: python${{ env.PYTHON_VERSION }}
          role: ${{ env.lambda-role-arn }}
          dry-run: false
